### ISSUE TITLE
Annouce

### ISSUE THREAD

**Issue by fade-dev** [Henry8K/Minescord#2]
When i try announce, and put in my image link it won't work. It says "Error announcing!
📑 • The link you entered does not exist or is not a valid link! Please try again later!"

**Comment by henrythierrydev** [comment]
> When i try announce, and put in my image link it won't work. It says "Error announcing! 📑 • The link you entered does not exist or is not a valid link! Please try again later!"

Hello, 

You must use a link image that ends in .PNG or .JPG and use a link with https://
